//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actuarial.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Actuarial.Common.Resource.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record added successfully.
        /// </summary>
        public static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment already exist.
        /// </summary>
        public static string Appointmentalreadyexist {
            get {
                return ResourceManager.GetString("Appointmentalreadyexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start with space..
        /// </summary>
        public static string CouldNotStartWithSpace {
            get {
                return ResourceManager.GetString("CouldNotStartWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted successfully.
        /// </summary>
        public static string DeleteSuccessfully {
            get {
                return ResourceManager.GetString("DeleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id Already Exist.
        /// </summary>
        public static string EmailIdAlreadyExist {
            get {
                return ResourceManager.GetString("EmailIdAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter 10 to 15 digits alpha-numeric value.
        /// </summary>
        public static string EnterBetweeen10to15 {
            get {
                return ResourceManager.GetString("EnterBetweeen10to15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter 8 digits numeric value.
        /// </summary>
        public static string EnterOnly8 {
            get {
                return ResourceManager.GetString("EnterOnly8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string FormattedRequired {
            get {
                return ResourceManager.GetString("FormattedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error Occured..
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Details.
        /// </summary>
        public static string InvalidDetails {
            get {
                return ResourceManager.GetString("InvalidDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string InvalidEmailRegularExp {
            get {
                return ResourceManager.GetString("InvalidEmailRegularExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model is not valid.
        /// </summary>
        public static string InvalidModel {
            get {
                return ResourceManager.GetString("InvalidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number..
        /// </summary>
        public static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number should starts from 04 and of 10 digits..
        /// </summary>
        public static string InvalidNumberForAurstralia {
            get {
                return ResourceManager.GetString("InvalidNumberForAurstralia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter experiance less than 90 years..
        /// </summary>
        public static string InvalidYearOfExperienceNumber {
            get {
                return ResourceManager.GetString("InvalidYearOfExperienceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Length Exceeded.
        /// </summary>
        public static string MaximumLengthExceeded {
            get {
                return ResourceManager.GetString("MaximumLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 1000 character allowed..
        /// </summary>
        public static string MaximumLengthExceeded1000 {
            get {
                return ResourceManager.GetString("MaximumLengthExceeded1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 10000 character allowed..
        /// </summary>
        public static string MaximumLengthExceeded10000 {
            get {
                return ResourceManager.GetString("MaximumLengthExceeded10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 50 character allowed..
        /// </summary>
        public static string MaximumLengthExceeded50 {
            get {
                return ResourceManager.GetString("MaximumLengthExceeded50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 500 character allowed..
        /// </summary>
        public static string MaximumLengthExceeded500 {
            get {
                return ResourceManager.GetString("MaximumLengthExceeded500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Length 100 Allowed..
        /// </summary>
        public static string MaxLength100 {
            get {
                return ResourceManager.GetString("MaxLength100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found..
        /// </summary>
        public static string NoRecordFound {
            get {
                return ResourceManager.GetString("NoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found for this user..
        /// </summary>
        public static string NoRecordFoundUser {
            get {
                return ResourceManager.GetString("NoRecordFoundUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No space allowed..
        /// </summary>
        public static string NoSpaceAllowed {
            get {
                return ResourceManager.GetString("NoSpaceAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No special characters allowed as input..
        /// </summary>
        public static string NoSpecialCharactersAllowed {
            get {
                return ResourceManager.GetString("NoSpecialCharactersAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-9 a-z A-Z &apos;&apos;-&apos;.,() values allowed..
        /// </summary>
        public static string OnlyContainsValueAllowed {
            get {
                return ResourceManager.GetString("OnlyContainsValueAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-99.
        /// </summary>
        public static string OnlyIntegers {
            get {
                return ResourceManager.GetString("OnlyIntegers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Username or Password.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password does not match.
        /// </summary>
        public static string PasswordMatch {
            get {
                return ResourceManager.GetString("PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated successfully. Please login with new password..
        /// </summary>
        public static string PasswordUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status changed successfully.
        /// </summary>
        public static string StatusChangedSuccessfully {
            get {
                return ResourceManager.GetString("StatusChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record updated successfully.
        /// </summary>
        public static string UpdateSuccessfully {
            get {
                return ResourceManager.GetString("UpdateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details..
        /// </summary>
        public static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field value should not start with space..
        /// </summary>
        public static string ValueNotStartWithSpace {
            get {
                return ResourceManager.GetString("ValueNotStartWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong current password..
        /// </summary>
        public static string WrongOldPassword {
            get {
                return ResourceManager.GetString("WrongOldPassword", resourceCulture);
            }
        }
    }
}
