//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actuarial.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Actuarial.Common.Resource.UserResource", typeof(UserResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail ID is disabled. Please contact your admin..
        /// </summary>
        public static string AccountDisabled {
            get {
                return ResourceManager.GetString("AccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email-id already exists for another user..
        /// </summary>
        public static string EmailAlreadyExist {
            get {
                return ResourceManager.GetString("EmailAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email-id already exists for another sole proprietor agent..
        /// </summary>
        public static string EmailAlreadyExistForSoleProprietor {
            get {
                return ResourceManager.GetString("EmailAlreadyExistForSoleProprietor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while sending forgot email to user..
        /// </summary>
        public static string ErrorOccuredWhileSendingMail {
            get {
                return ResourceManager.GetString("ErrorOccuredWhileSendingMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password email sent successfully with activation link..
        /// </summary>
        public static string ForgotPasswordEmailWithActivationLink {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailWithActivationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 15 character allowed..
        /// </summary>
        public static string MaximumLength15 {
            get {
                return ResourceManager.GetString("MaximumLength15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 50 character allowed..
        /// </summary>
        public static string MaximumLength50 {
            get {
                return ResourceManager.GetString("MaximumLength50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length exceeded..
        /// </summary>
        public static string MaximumLengthExceeded {
            get {
                return ResourceManager.GetString("MaximumLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification send successfully.
        /// </summary>
        public static string NotificationSendSuccessfully {
            get {
                return ResourceManager.GetString("NotificationSendSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alphabets allowed..
        /// </summary>
        public static string OnlyAlphabetics {
            get {
                return ResourceManager.GetString("OnlyAlphabetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated successfully..
        /// </summary>
        public static string PasswordUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phone number is already exist..
        /// </summary>
        public static string PhoneNumberAlreadyExist {
            get {
                return ResourceManager.GetString("PhoneNumberAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan adopted successfully..
        /// </summary>
        public static string PlanAdoptedSuccessfully {
            get {
                return ResourceManager.GetString("PlanAdoptedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings updated successfully..
        /// </summary>
        public static string SettingsUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("SettingsUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup Step 1 completed successfully..
        /// </summary>
        public static string SignUpFirstStep {
            get {
                return ResourceManager.GetString("SignUpFirstStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup Step 4 completed successfully..
        /// </summary>
        public static string SignUpFourthStep {
            get {
                return ResourceManager.GetString("SignUpFourthStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup process completed successfully. A verification link send to your registered email. Please verify your account to access your dashboard ..
        /// </summary>
        public static string SignupSuccessfully {
            get {
                return ResourceManager.GetString("SignupSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup Step 3 completed successfully..
        /// </summary>
        public static string SignUpThirdStep {
            get {
                return ResourceManager.GetString("SignUpThirdStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a subscription plan.
        /// </summary>
        public static string SubscriptionRequired {
            get {
                return ResourceManager.GetString("SubscriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details..
        /// </summary>
        public static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist..
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details Updated Successfully..
        /// </summary>
        public static string UserUpdateSuccessfully {
            get {
                return ResourceManager.GetString("UserUpdateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification is pending. Please your inbox to verify your account..
        /// </summary>
        public static string VerificationPending {
            get {
                return ResourceManager.GetString("VerificationPending", resourceCulture);
            }
        }
    }
}
